# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/get-embeddings',
                'doc_host': 'https://gautam-e.github.io',
                'git_url': 'https://github.com/gautam-e/get-embeddings',
                'lib_path': 'get_embeddings'},
  'syms': {'get_embeddings.core': {'get_embeddings.core.foo': ('core.html#foo', 'get_embeddings/core.py')}}}
